# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Site settings
title: "Pieter Brandwijk - Software Quality Consultant"
first_name: Pieter
last_name: Brandwijk
email: pieter@pbrandwijk.com
pgp_fingerprint: "B8 7C 2D 27 91 28 11 DE FF 53 D7 3A 4C B4 07 5B 9F AD 44 A8"
sip: p.brandwijk@sip.linphone.org
tel: "+34 693 720 739"
profession: "Software Engineer"
description: > # this means to ignore newlines until "baseurl:"
  Personal blog of Pieter Brandwijk.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.pbrandwijk.com" # the base hostname & protocol for your site

# Social media handles
feedburner_url: "http://feeds.feedburner.com/PieterBrandwijkBlog"
github_username: "pbrandwijk"
github_url: "https://github.com/pbrandwijk"
gitlab_username: "pbrandwijk"
gitlab_url: "https://gitlab.com/pbrandwijk"
bitbucket_username: "pbrandwijk"
bitbucket_url: "https://bitbucket.org/pbrandwijk"
linkedin_url: "https://www.linkedin.com/in/pbrandwijk"
skype_username: "pieter_1923"

# Set the permalink style
permalink: /:year/:month/:day/:title:output_ext

# Build settings
# theme: minima
markdown: kramdown
plugins: 
 - jekyll-tidy
 - jekyll-feed

# Set KaTex as the math engine for Kramdown
kramdown:
  math_engine: katex

# Add the collection definition for projects and articles
collections:
  projects:
    output: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
